version: '3.10'

services:
  fastapi:
    container_name: fastapi_container
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:ows1234@mysqldb/BigFast_db
    depends_on:
      - mysqldb
    networks:
      - ft

  mysqldb:
    container_name: mysqldb_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ows1234
      MYSQL_DATABASE: BigFast_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ft

networks:
  ft:
    driver: bridge

volumes:
  mysql_data:
